// ============================================================
// ARIA LEAD INJECTOR — KaloData Batch (March 5, 2026)
// Paste this entire script into your browser console while
// ARIA Dashboard is open, then refresh the page.
// ============================================================

(function () {
  const today = '2026-03-05';
  const day3  = '2026-03-08';
  const day7  = '2026-03-12';

  function makeFollowUps() {
    return [
      { day: 3,  action: 'Send Day 3 follow-up DM',         status: 'pending', scheduledDate: day3 },
      { day: 7,  action: 'Send Day 7 follow-up if no reply', status: 'pending', scheduledDate: day7 },
    ];
  }

  function score(rp, bf, ec, pm) {
    const overall = Math.round((rp * 0.35 + bf * 0.25 + ec * 0.20 + pm * 0.20) * 10) / 10;
    return { revenuePotential: rp, brandFit: bf, easeOfClosing: ec, productMargins: pm, overall };
  }

  const newLeads = [
    {
      brandName: 'DHG LIVING',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'home',
      productType: 'Home & Living',
      estimatedMonthlyGmv: 10010,
      kaloDataGmv: 10010,
      commissionRate: 10,
      status: 'new',
      score: score(8, 6, 5, 6),
      brief: {
        brandOverview: 'Home & Living brand with explosive >999% revenue growth. 401 products, avg unit price $24.96.',
        fitAnalysis: 'Home goods work well in LIVE demos. High growth signals momentum — brand is scaling fast and may be open to agency support.',
        recommendedPitchAngle: 'Lead with LIVE selling — home products are highly demonstrable. Highlight creator program to sustain growth.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: >999.9% growth, 401 items sold, $24.96 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'BOGOMORE',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10130,
      kaloDataGmv: 10130,
      commissionRate: 10,
      status: 'new',
      score: score(8, 5, 5, 7),
      brief: {
        brandOverview: 'Explosive >999% revenue growth. 258 products sold, avg unit price $39.26.',
        fitAnalysis: 'Extreme growth rate signals a brand on the rise. Category unknown — research their TikTok Shop before outreach.',
        recommendedPitchAngle: 'Lead with LIVE selling momentum story. High growth brands respond well to "scale even faster" pitch.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: >999.9% growth, 258 items sold, $39.26 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Black Selected Store',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'fashion',
      productType: 'Fashion & Apparel',
      estimatedMonthlyGmv: 10080,
      kaloDataGmv: 10080,
      commissionRate: 10,
      status: 'new',
      score: score(8, 7, 5, 5),
      brief: {
        brandOverview: 'Fashion brand with 679.6% revenue growth. 652 items sold, avg unit price $15.46.',
        fitAnalysis: 'Fashion is a top LIVE selling category. High growth + fashion = strong fit. Low unit price means volume is key.',
        recommendedPitchAngle: 'Lead with LIVE selling — fashion demos convert extremely well. Pitch creator program for UGC volume.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 679.6% growth, 652 items sold, $15.46 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'WENDMONDS Store',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10170,
      kaloDataGmv: 10170,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 7),
      brief: {
        brandOverview: '430.4% revenue growth. 185 items sold, avg unit price $55.00.',
        fitAnalysis: 'Strong growth with a solid unit price ($55 avg). Higher price point means better commission potential.',
        recommendedPitchAngle: 'Pitch LIVE selling with a premium demo angle. Higher price products benefit from live demos that overcome buyer hesitation.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 430.4% growth, 185 items sold, $55.00 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Foot Rhythm',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'health',
      productType: 'Health & Wellness',
      estimatedMonthlyGmv: 10090,
      kaloDataGmv: 10090,
      commissionRate: 10,
      status: 'new',
      score: score(7, 8, 5, 8),
      brief: {
        brandOverview: 'Health/foot care brand with 416.2% revenue growth. 138 items sold, avg unit price $73.15.',
        fitAnalysis: 'Health products with high unit price ($73) = excellent margin potential. Strong growth. LIVE demos work great for health gadgets.',
        recommendedPitchAngle: 'Lead with LIVE selling — health product demos build trust and drive conversions. Creator UGC for social proof.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 416.2% growth, 138 items sold, $73.15 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'MSTARKE',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10010,
      kaloDataGmv: 10010,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 6),
      brief: {
        brandOverview: '406.8% revenue growth. 451 items sold, avg unit price $22.20.',
        fitAnalysis: 'Very fast growing brand. Category unclear — research TikTok Shop before outreach to personalize pitch.',
        recommendedPitchAngle: 'Lead with growth acceleration story. Frame LIVE selling as the next step to keep momentum going.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 406.8% growth, 451 items sold, $22.20 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'beenuvo',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10050,
      kaloDataGmv: 10050,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 6),
      brief: {
        brandOverview: '298.6% revenue growth. 397 items sold, avg unit price $25.31.',
        fitAnalysis: 'Strong growth trajectory. Research category on TikTok to tailor pitch.',
        recommendedPitchAngle: 'Lead with LIVE selling to sustain and accelerate their growth curve.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 298.6% growth, 397 items sold, $25.31 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'TruSkin',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'beauty',
      productType: 'Skincare',
      estimatedMonthlyGmv: 10160,
      kaloDataGmv: 10160,
      commissionRate: 10,
      status: 'new',
      score: score(7, 9, 6, 6),
      brief: {
        brandOverview: 'Skincare brand with 101.5% revenue growth. 526 items sold, avg unit price $19.31.',
        fitAnalysis: 'Beauty/skincare is the #1 LIVE selling category on TikTok Shop. Strong growth + established brand name = prime prospect.',
        recommendedPitchAngle: 'Lead with LIVE selling — skincare demos (before/after, texture, application) convert extremely well. Pair with creator UGC program.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 101.5% growth, 526 items sold, $19.31 avg price (Feb 02 – Mar 03 2026). Priority: Beauty category.',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'XMONDO Hair',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'beauty',
      productType: 'Hair Care',
      estimatedMonthlyGmv: 10120,
      kaloDataGmv: 10120,
      commissionRate: 10,
      status: 'new',
      score: score(6, 9, 6, 7),
      brief: {
        brandOverview: 'Hair care brand with 89.6% revenue growth. 319 items sold, avg unit price $31.74.',
        fitAnalysis: 'Hair care is top-performing in LIVE selling. $31 avg price is solid for commission. Growing well.',
        recommendedPitchAngle: 'Lead with LIVE selling hair transformation demos. Creator UGC for before/after content drives massive social proof.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 89.6% growth, 319 items sold, $31.74 avg price (Feb 02 – Mar 03 2026). Priority: Beauty/Hair category.',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Fragrance Story INC',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'beauty',
      productType: 'Fragrance & Perfume',
      estimatedMonthlyGmv: 10060,
      kaloDataGmv: 10060,
      commissionRate: 10,
      status: 'new',
      score: score(6, 9, 6, 8),
      brief: {
        brandOverview: 'Fragrance/perfume brand with 67.6% revenue growth. 137 items sold, avg unit price $73.46.',
        fitAnalysis: 'High unit price ($73) = great commission per sale. Fragrance brands benefit hugely from LIVE storytelling and scent demos. Beauty category.',
        recommendedPitchAngle: 'Lead with LIVE selling — fragrance sells through story and emotion, perfect for LIVE format. Creator gifting amplifies reach.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 67.6% growth, 137 items sold, $73.46 avg price (Feb 02 – Mar 03 2026). Priority: Beauty/Fragrance, high unit price.',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Slim Perform Elite',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'health',
      productType: 'Fitness & Slimming',
      estimatedMonthlyGmv: 10040,
      kaloDataGmv: 10040,
      commissionRate: 10,
      status: 'new',
      score: score(7, 8, 5, 7),
      brief: {
        brandOverview: 'Fitness/slimming brand with 135.5% revenue growth. 327 items sold, avg unit price $30.69.',
        fitAnalysis: 'Health & fitness products perform very well in LIVE selling. Growing fast, good price point.',
        recommendedPitchAngle: 'Lead with LIVE selling product demos and transformation stories. Creator UGC for results-based social proof.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 135.5% growth, 327 items sold, $30.69 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Seat Hoodie',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'fashion',
      productType: 'Fashion Apparel',
      estimatedMonthlyGmv: 10010,
      kaloDataGmv: 10010,
      commissionRate: 10,
      status: 'new',
      score: score(7, 7, 5, 7),
      brief: {
        brandOverview: 'Fashion brand (hoodies/apparel) with 184.9% revenue growth. 328 items sold, avg unit price $30.51.',
        fitAnalysis: 'Fashion apparel is a top LIVE category. Fast growing and solid price point. Hoodies are highly demonstrable on LIVE.',
        recommendedPitchAngle: 'Lead with LIVE selling — apparel try-ons and styling sessions drive strong conversions. Creator UGC for style content.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 184.9% growth, 328 items sold, $30.51 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Exercise with me',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'health',
      productType: 'Fitness & Exercise',
      estimatedMonthlyGmv: 10020,
      kaloDataGmv: 10020,
      commissionRate: 10,
      status: 'new',
      score: score(7, 8, 5, 5),
      brief: {
        brandOverview: 'Fitness brand with 194.2% revenue growth. 602 items sold, avg unit price $16.64.',
        fitAnalysis: 'Fitness products work well in LIVE. High volume seller (602 items). Growing fast.',
        recommendedPitchAngle: 'Lead with LIVE selling fitness product demos. Creator program for workout influencers to show results.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 194.2% growth, 602 items sold, $16.64 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'LULULOOK',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'beauty',
      productType: 'Beauty Accessories',
      estimatedMonthlyGmv: 10110,
      kaloDataGmv: 10110,
      commissionRate: 10,
      status: 'new',
      score: score(7, 9, 6, 7),
      brief: {
        brandOverview: 'Beauty brand with 143.2% revenue growth. 222 items sold, avg unit price $45.53.',
        fitAnalysis: 'Beauty + $45 avg price + fast growth = strong fit. High unit price means better commission per sale.',
        recommendedPitchAngle: 'Lead with LIVE selling beauty demos. Creator gifting for UGC is natural for beauty brands.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 143.2% growth, 222 items sold, $45.53 avg price (Feb 02 – Mar 03 2026). Priority: Beauty category.',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'WHATOOK US',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10070,
      kaloDataGmv: 10070,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 6),
      brief: {
        brandOverview: '114.4% revenue growth. 530 items sold, avg unit price $19.00.',
        fitAnalysis: 'Growing strongly. Category unclear — check TikTok Shop to determine product fit before outreach.',
        recommendedPitchAngle: 'Research product category first. Lead with LIVE selling for fastest pitch to market.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 114.4% growth, 530 items sold, $19.00 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Chic Novelties',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'Novelty & Gifts',
      estimatedMonthlyGmv: 10000,
      kaloDataGmv: 10000,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 5),
      brief: {
        brandOverview: 'Novelty/gifts brand with 115.6% revenue growth. 698 items sold, avg unit price $14.33.',
        fitAnalysis: 'Growing fast. Gift/novelty items can work well in LIVE for impulse purchases.',
        recommendedPitchAngle: 'Lead with LIVE selling impulse-buy angle. Creator UGC for "gift idea" content.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 115.6% growth, 698 items sold, $14.33 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Toni Crafter',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'Crafts & DIY',
      estimatedMonthlyGmv: 10170,
      kaloDataGmv: 10170,
      commissionRate: 10,
      status: 'new',
      score: score(7, 5, 5, 5),
      brief: {
        brandOverview: 'Crafts/DIY brand with 160.5% revenue growth. 693 items sold, avg unit price $14.67.',
        fitAnalysis: 'High volume, fast growth. Craft products can work well in LIVE demos showing how-to.',
        recommendedPitchAngle: 'Lead with LIVE selling tutorial/demo angle. Craft demonstrations are naturally engaging on LIVE.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 160.5% growth, 693 items sold, $14.67 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'CuLiDingUS',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10160,
      kaloDataGmv: 10160,
      commissionRate: 10,
      status: 'new',
      score: score(6, 5, 5, 7),
      brief: {
        brandOverview: '96.6% revenue growth. 188 items sold, avg unit price $54.03.',
        fitAnalysis: 'Good unit price ($54) = solid commission potential. Growing well. Research category before outreach.',
        recommendedPitchAngle: 'Lead with LIVE selling. Higher price point benefits from LIVE demo to overcome purchase hesitation.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 96.6% growth, 188 items sold, $54.03 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'FUFUSQUISHY',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'Toys & Collectibles',
      estimatedMonthlyGmv: 10130,
      kaloDataGmv: 10130,
      commissionRate: 10,
      status: 'new',
      score: score(6, 5, 5, 7),
      brief: {
        brandOverview: 'Squishy toys/collectibles brand with 91.7% revenue growth. 270 items sold, avg unit price $37.52.',
        fitAnalysis: 'Toys/collectibles have strong LIVE impulse-buy potential. Growing well with solid unit price.',
        recommendedPitchAngle: 'Lead with LIVE selling unboxing/collection reveal angle. Creator UGC for toy review content.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 91.7% growth, 270 items sold, $37.52 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
    {
      brandName: 'Lanisty',
      contactName: '', contactRole: '', email: '', phone: '',
      tiktokHandle: '', website: '',
      productCategory: 'other',
      productType: 'General',
      estimatedMonthlyGmv: 10140,
      kaloDataGmv: 10140,
      commissionRate: 10,
      status: 'new',
      score: score(5, 5, 5, 6),
      brief: {
        brandOverview: '49.8% revenue growth. 462 items sold, avg unit price $21.94.',
        fitAnalysis: 'Steady growth. Research category before outreach to personalize the pitch.',
        recommendedPitchAngle: 'Lead with LIVE selling to accelerate their steady growth into a steeper curve.',
        followUpSchedule: makeFollowUps(),
      },
      notes: 'KaloData: 49.8% growth, 462 items sold, $21.94 avg price (Feb 02 – Mar 03 2026)',
      source: 'KaloData',
      tiktokShopUrl: '',
      createdAt: today, updatedAt: today,
    },
  ].map(lead => ({ ...lead, id: crypto.randomUUID() }));

  // Read existing leads from localStorage
  const raw = localStorage.getItem('aria-leads');
  const existing = raw ? JSON.parse(raw) : { state: { leads: [] }, version: 0 };

  // Merge new leads in
  existing.state.leads = [...existing.state.leads, ...newLeads];
  localStorage.setItem('aria-leads', JSON.stringify(existing));

  console.log(`✅ Successfully injected ${newLeads.length} leads into ARIA.`);
  console.log('Refresh the page to see them in your Leads module.');
})();
